// This file was auto-generated by ML.NET Model Builder. 

using System;
using MLB_01ML.Model;

namespace MLB_01ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            while (true)
            {
                CheckForReviewAndPredict();
            };
        }

        private static void CheckForReviewAndPredict()
        {
            Console.WriteLine("Please enter your review: ");
            var input = Console.ReadLine();

            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Col0 = input,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            if (predictionResult.Prediction == "0")
            {
                Console.WriteLine($"With a certainity of {String.Format("{000:F1}", predictionResult.Score[0] * 100)}% this was a NEGATIVE review!");
            }
            else
            {
                Console.WriteLine($"With a certainity of {String.Format("{000:F1}", predictionResult.Score[1] * 100)}% this was a POSITIVE review!");
            }
        }
    }
}
